# Generated by Django 5.2.5 on 2025-09-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_prediction_unique_together_remove_match_b365a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='B365A',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='B365D',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='B365H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='XBA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='XBD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='XBH',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
