# Generated by Django 5.2.5 on 2025-09-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_b365a_match_b365d_match_b365h_match_xba_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='XBA',
        ),
        migrations.RemoveField(
            model_name='match',
            name='XBD',
        ),
        migrations.RemoveField(
            model_name='match',
            name='XBH',
        ),
    ]
